In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
import os
os.chdir('/content/gdrive/My Drive/MNISTBrain/')
print(os.listdir())

['MW.txt', 'MW.csv', 'MW_np.csv', 'MW_np.npy', 'MW_np_01.npy', 'MindBigData-IN-v1.06 (1).zip', 'IN.txt', 'IN', 'Untitled1.ipynb', 'MindBigData-EP-v1.0.zip', 'EP1_01.txt', 'EP', 'Untitled0.ipynb', 'EP_data_ready.npy', 'EP_label_ready.npy', 'EP_preprocessing.ipynb', 'MNISTBrain.ipynb']


In [ ]:
import numpy as np 
data = np.load("/content/gdrive/My Drive/MNISTBrain/EP_data_ready.npy")
data

array([[[4372.307692, 4445.128205, 4560.      , ..., 4645.641025,
         3990.769231, 4075.384615],
        [4375.384615, 4449.743589, 4563.076923, ..., 4655.384615,
         3994.871795, 4078.974358],
        [4376.410256, 4450.25641 , 4563.589743, ..., 4658.461538,
         3990.256411, 4076.923076],
        ...,
        [4380.      , 4503.589743, 4573.333333, ..., 4665.128205,
         3988.717949, 4066.666666],
        [4378.461538, 4496.923076, 4570.76923 , ..., 4659.487179,
         3982.564103, 4065.128205],
        [4383.076923, 4503.589743, 4574.871794, ..., 4660.      ,
         3977.948718, 4065.128205]],

       [[4408.717948, 4533.846153, 4597.435897, ..., 4686.666666,
         3992.820513, 4090.25641 ],
        [4410.25641 , 4532.307692, 4600.51282 , ..., 4686.666666,
         4001.025641, 4094.871794],
        [4409.743589, 4524.615384, 4597.948717, ..., 4686.666666,
         4010.76923 , 4092.820512],
        ...,
        [4383.589743, 4482.564102, 4569.230769, ..., 4

In [ ]:
print(type(data))
print(data.ndim)
print(data.shape)

<class 'numpy.ndarray'>
3
(44656, 256, 14)


In [ ]:
label = np.load("/content/gdrive/My Drive/MNISTBrain/EP_label_ready.npy")
label

array([3., 1., 2., ..., 3., 7., 6.])

In [ ]:
print(type(label))
print(label.ndim)
print(label.shape)

<class 'numpy.ndarray'>
1
(44656,)


In [ ]:
max = np.amax(data, axis = 0)
print(max)
min = np.amin(data, axis = 0)
print(min)
#max = np.reshape(max , (max.shape[0] , 1))
#print(max)
#min = np.reshape(min , (min.shape[0] , 1))
#print(min)
data = (data - min)/(max - min)
print(data)

[[6147.483647 6147.483647 6141.025641 ... 6147.483647 6147.483647
  5786.153846]
 [6147.483647 6147.483647 6136.923076 ... 6147.483647 6147.483647
  5783.589743]
 [6147.483647 6147.483647 6130.25641  ... 6147.483647 6147.483647
  5774.358974]
 ...
 [6147.483647 6147.483647 6147.483647 ... 6147.483647 6147.483647
  5832.307692]
 [6147.483647 6147.483647 6147.483647 ... 6147.483647 6147.483647
  5828.717948]
 [6147.483647 6147.483647 6147.483647 ... 6147.483647 6147.483647
  5820.      ]]
[[1852.516352 1852.516352 3814.358975 ... 1852.516352 1852.516352
  2204.615385]
 [1852.516352 1852.516352 3818.461539 ... 1852.516352 1852.516352
  2226.666667]
 [1852.516352 1852.516352 3817.435898 ... 1852.516352 1852.516352
  2237.435898]
 ...
 [   0.          0.          0.       ...    0.          0.
     0.      ]
 [   0.          0.          0.       ...    0.          0.
     0.      ]
 [   0.          0.          0.       ...    0.          0.
     0.      ]]
[[[0.58668464 0.60363949 0.3204760

In [ ]:
from tensorflow.keras.utils import to_categorical 
L = to_categorical(label)
print(L)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
trainX = data[6000:] 
trainY = L[6000:]
testX = data[:6000]
testY = L[:6000]
print(trainX,trainY,testX,testY)

[[[0.58811744 0.61880333 0.33744765 ... 0.65187722 0.40209173 0.51804124]
  [0.58728164 0.61808693 0.33510285 ... 0.65008621 0.40018132 0.51297578]
  [0.58740104 0.61856453 0.33702882 ... 0.64984741 0.39946492 0.5122517 ]
  ...
  [0.7139882  0.73751252 0.74960836 ... 0.75920161 0.59711736 0.69823266]
  [0.71432188 0.73767936 0.7497752  ... 0.75895135 0.59845208 0.69848671]
  [0.71407162 0.73759594 0.74885758 ... 0.75836741 0.5985355  0.69979734]]

 [[0.58369963 0.61928093 0.33061494 ... 0.64960861 0.41725557 0.51446163]
  [0.58549064 0.62023613 0.33421809 ... 0.65175782 0.41833017 0.51326413]
  [0.58752044 0.62166894 0.33769401 ... 0.65295182 0.41988238 0.51515151]
  ...
  [0.71056799 0.73217367 0.7501923  ... 0.75528089 0.59419768 0.69084674]
  [0.7093167  0.73075553 0.74877416 ... 0.75469695 0.59436452 0.69065634]
  [0.7093167  0.73092237 0.74835707 ... 0.7536125  0.59286297 0.69151467]]

 [[0.58847564 0.61772873 0.34560282 ... 0.65199662 0.41880778 0.51546392]
  [0.58931145 0.618922

In [ ]:
batch_size = 16
num_classes = 10
epochs = 100
input_shape=(trainX.shape[1], 14)

In [ ]:
import keras
from keras.models import Model
from keras.models import Sequential
from keras.layers import Conv1D, ZeroPadding1D, MaxPooling1D, BatchNormalization, Activation, Dropout, Flatten, Dense

In [ ]:
model = Sequential()
intput_shape=(trainX.shape[1], 14)
model.add(Conv1D(8, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(BatchNormalization())
model.add(MaxPooling1D(pool_size=(2)))
model.add(Conv1D(8,kernel_size=3, activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling1D(pool_size=(2)))
model.add(Conv1D(8,kernel_size=3, activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling1D(pool_size=(2)))
model.add(Conv1D(8,kernel_size=3, activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling1D(pool_size=(2)))
model.add(Conv1D(4,kernel_size=3, activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling1D(pool_size=(2)))
model.add(Flatten())
#model.add(Dense(8, activation='relu'))
#model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 254, 8)            344       
_________________________________________________________________
batch_normalization (BatchNo (None, 254, 8)            32        
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 127, 8)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 125, 8)            200       
_________________________________________________________________
batch_normalization_1 (Batch (None, 125, 8)            32        
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 62, 8)             0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 60, 8)             2

In [ ]:
from keras import optimizers

adam = optimizers.Adam(learning_rate=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(optimizer=adam , loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(trainX, trainY, epochs=1, verbose=1 , validation_data = (testX, testY))

1208/1208 [==============================] - 53s 6ms/step - loss: 2.4523 - accuracy: 0.1023 - val_loss: 2.3678 - val_accuracy: 0.1045


In [ ]:
model.evaluate(testX , testY , verbose = 1)

188/188 [==============================] - 1s 3ms/step - loss: 2.3678 - accuracy: 0.1045


[2.367769718170166, 0.10450000315904617]

In [ ]:
from keras import backend as K
import numpy as np

layer_of_interest=0
intermediate_tensor_function = K.function([model.layers[0].input],[model.layers[layer_of_interest].output])
intermediate_tensor = intermediate_tensor_function(trainX[0:])[0]

In [ ]:
intermediates = []
color_intermediates = []
for i in range(len(trainX)):
    output_class = np.argmax(trainY[i:])
    intermediate_tensor = intermediate_tensor_function(trainX[i:])[0]
    intermediates.append(intermediate_tensor[0])
    if(output_class == 0):
        color_intermediates.append("#0000ff")
    else:
        color_intermediates.append("#ff0000")