In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
#import the neccessary modules
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import math

In [3]:
df_train = pd.read_excel('/content/drive/My Drive/data/13.xlsx')
df_test = pd.read_excel('/content/drive/My Drive/data/14.xlsx')

In [4]:
df_train.head()

N    V   TA        Force     GS
0  1120   50  0.0  2900.996825  16.87
1  1120   50  1.5  4491.879480  17.14
2  1400   63  2.5  4482.221886  23.38
3  1400   80  0.0  2808.288887  16.85
4   710  200  0.0  1593.452836   8.82

In [5]:
#Let's get some more information about the dataset
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138121 entries, 0 to 138120
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   N       138121 non-null  int64  
 1   V       138121 non-null  int64  
 2   TA      138121 non-null  float64
 3   Force   138121 non-null  float64
 4   GS      138121 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 5.3 MB


In [6]:
#Let's get some information about the missing values
df_train['N'].value_counts()

710     40937
1120    39428
1400    29803
900     27953
Name: N, dtype: int64

In [7]:
#Let's get some information about the missing values
df_train['V'].value_counts()

50     71877
80     16089
160    15123
63     14480
200    12323
315     4578
250     3651
Name: V, dtype: int64

In [8]:
#Let's get some information about the missing values
df_train['TA'].value_counts()

0.0    50305
2.5    47673
1.5    40143
Name: TA, dtype: int64

In [9]:
#Let's get some information about the missing values
df_train['Force'].value_counts()

1303.415119    1
4675.941377    1
2438.740427    1
3046.627603    1
3842.226969    1
              ..
3645.071058    1
3767.349265    1
3235.115495    1
3984.415842    1
2491.512766    1
Name: Force, Length: 138121, dtype: int64

In [10]:
#Let's get some information about the missing values
df_train['GS'].value_counts()

19.33    9601
12.45    9601
18.82    9601
17.14    8641
14.99    8641
9.52     8608
16.87    8608
11.42    8577
23.38    7621
19.92    6859
14.24    6061
17.73    5401
14.70    5344
16.85    5344
9.24     3360
12.16    3001
11.32    2701
8.82     2688
13.53    2672
11.49    2401
16.70    2401
14.51    2161
17.21    1921
13.72    1729
16.11    1680
20.06    1525
16.45    1373
Name: GS, dtype: int64

In [11]:
df_test.head()

N    V   TA        Force     GS
0  900  250  0.0  4211.182857  14.99
1  900  250  0.0  4214.700022  14.99
2  900  250  0.0  4215.838816  14.99
3  900  250  0.0  4215.818721  14.99
4  900  250  0.0  4215.311837  14.99

In [12]:
X_train = df_train[['N','V','TA', 'Force']].values
X_train

array([[1.12000000e+03, 5.00000000e+01, 0.00000000e+00, 2.90099682e+03],
       [1.12000000e+03, 5.00000000e+01, 1.50000000e+00, 4.49187948e+03],
       [1.40000000e+03, 6.30000000e+01, 2.50000000e+00, 4.48222189e+03],
       ...,
       [7.10000000e+02, 1.60000000e+02, 0.00000000e+00, 3.45658777e+03],
       [7.10000000e+02, 2.00000000e+02, 0.00000000e+00, 2.01022588e+03],
       [1.12000000e+03, 5.00000000e+01, 2.50000000e+00, 7.85161113e+02]])

In [13]:
Y_train = df_train['GS'].values
Y_train

array([16.87, 17.14, 23.38, ...,  9.24,  8.82, 19.33])

In [14]:
X_test = df_test[['N','V','TA', 'Force']].values
X_test

array([[9.00000000e+02, 2.50000000e+02, 0.00000000e+00, 4.21118286e+03],
       [9.00000000e+02, 2.50000000e+02, 0.00000000e+00, 4.21470002e+03],
       [9.00000000e+02, 2.50000000e+02, 0.00000000e+00, 4.21583882e+03],
       ...,
       [1.40000000e+03, 8.00000000e+01, 2.50000000e+00, 5.02849443e+03],
       [1.40000000e+03, 8.00000000e+01, 2.50000000e+00, 5.02559050e+03],
       [1.40000000e+03, 8.00000000e+01, 2.50000000e+00, 5.02315948e+03]])

In [15]:
Y_test = df_test['GS'].values
Y_test

array([14.99, 14.99, 14.99, ..., 20.14, 20.14, 20.14])

In [16]:
# import the neccessary module to build neural network
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
#from keras.optimizers import SGD
from keras.callbacks import EarlyStopping
from sklearn.model_selection import cross_val_score
from keras import backend as K
from keras.layers import BatchNormalization
seed = 123456

In [17]:
# define the keras model
model = Sequential()
model.add(Dense(32, input_dim=4, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='linear'))

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                160       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 5         
Total params: 865
Trainable params: 865
Non-trainable params: 0
_________________________________________________________________


In [19]:
# compile the keras model
model.compile(loss='mean_squared_error', optimizer='rmsprop')

In [20]:
# fit the keras model on the dataset
history=model.fit(X_train, Y_train, epochs=10, batch_size=100, verbose=1)

Epoch 1/10
1382/1382 [==============================] - 6s 4ms/step - loss: 55.2457
Epoch 2/10
1382/1382 [==============================] - 5s 3ms/step - loss: 4.1485
Epoch 3/10
1382/1382 [==============================] - 5s 4ms/step - loss: 3.5593
Epoch 4/10
1382/1382 [==============================] - 5s 4ms/step - loss: 3.2013
Epoch 5/10
1382/1382 [==============================] - 5s 4ms/step - loss: 2.8849
Epoch 6/10
1382/1382 [==============================] - 5s 4ms/step - loss: 2.5909
Epoch 7/10
1382/1382 [==============================] - 5s 3ms/step - loss: 2.3857
Epoch 8/10
1382/1382 [==============================] - 5s 3ms/step - loss: 2.2395
Epoch 9/10
1382/1382 [==============================] - 5s 3ms/step - loss: 2.1035
Epoch 10/10
1382/1382 [==============================] - 5s 3ms/step - loss: 1.9852


In [21]:
loss = history.history.get('loss')
acc = history.history.get('acc')
val_loss = history.history.get('val_loss')
val_acc = history.history.get('val_acc')

In [27]:
pred = model.predict(X_test, 100, verbose=1)
ans = [np.argmax(r) for r in Y_train[:]]
print(ans)

360/360 [==============================] - 0s 1ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,