# **Tensors**
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters

In [1]:
# initializing required libraries
%matplotlib inline
import torch
import numpy as np

### **Initializing a Tensor**
Tensors can be initialized in various ways. Let us learn one by one with some examples.

In [2]:
#Directly from data
##Tensors can be created directly from data. The data type is automatically inferred.
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
#From a NumPy array
##Tensors can be created from NumPy arrays and vice versa.
##Since, numpy 'np_array' and tensor 'x_np' share the same memory location here, changing the value for one will change the other.
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



In [5]:
# From another Tensor
## The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

x_zeros = torch.zeros_like(x_data, dtype=torch.float)
print(f"zeros Tensor: \n {x_zeros} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9950, 0.4723],
        [0.3530, 0.2471]]) 

zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.]]) 



In [7]:
# With random or constant values
## shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor. 
## Shape shows the number of rows and columns in the tensor. E.g. shape = (# of rows, # of columns).

shape = (2,3,)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {one_tensor} \n")
print(f"Zeros Tensor: \n {zero_tensor}")

Random Tensor: 
 tensor([[0.6777, 0.7177, 0.8809],
        [0.0125, 0.5541, 0.4655]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# Attributes of a Tensor
## Tensor attributes describe their shape, data type, and the device on which they are stored.
tensor = torch.rand(6,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Tensor is: \n {tensor} \n")

Shape of tensor: torch.Size([6, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Tensor is: 
 tensor([[0.9091, 0.5291, 0.4100, 0.5252],
        [0.2892, 0.0612, 0.3434, 0.7284],
        [0.5928, 0.2666, 0.1880, 0.8962],
        [0.7004, 0.1597, 0.1125, 0.5763],
        [0.0998, 0.3441, 0.3975, 0.5670],
        [0.2613, 0.0696, 0.3307, 0.5460]]) 



### **Operations on Tensor**

In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [11]:
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Let's try out some of the operations on our created tensors.

In [12]:
# Standard numpy-like indexing and slicing:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('Last roww: ', tensor[-1])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
Last roww:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
# Joining tensors
## We can use torch.cat to concatenate a sequence of tensors along a given dimension.
t1 = torch.cat([tensor, tensor, tensor], dim=-1)
print(t1)
## torch.stack is another tensor joining option that is subtly different from torch.cat.
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


### **Arithmatic Operations**


In [24]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T #.T = Transpose
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(f"With @ \n {y1} \n")
print(f"With matmul \n {y2} \n")
print(f"With matmul and out \n {y3} \n")

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f"With * \n {z1} \n")
print(f"With mul \n {z2} \n")
print(f"With mul and out \n {z3} \n")

With @ 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

With matmul 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

With matmul and out 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

With * 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

With mul 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

With mul and out 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [25]:
# Single element tensors
## If we have a one-element tensor, for example by aggregating all values of a tensor into one value, 
## you can convert it to a Python numerical value using item():

agg = tensor.sum()
agg_item = agg.item() 
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [26]:
# In-place operations
## Operations that store the result into the operand are called in-place. 
## They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

print(tensor, "\n")
tensor.add_(5)
print(tensor, "\n")
tensor.copy_(y2)
print(tensor,"\n")
tensor.t_()
print(tensor,"\n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

